info:
  title: HCCB Backend API
  version: '1.0'
openapi: 3.0.0
paths:
  /user/add:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                name:
                  type: string
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                data:
                  email: user1@test.com
                  id: cfJEpMmMXZZcjNmXu8x1
                  name: user1
                error: None
          description: Add one user
        '503':
          content:
            application/json:
              example:
                data: None
                error: |
                  Traceback (most recent call last):
                      File "/home/source/Workspace/Python/hccb-backend/src/resolvers/user.py", line 38, in post
                      user.email = data['email']
                  KeyError: 'email'
          description: Error
  /user/delete:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                id:
                  type: string
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                error:
                  data:
                    - users:
                        - user0@test.com
                        - user1@test.com
                        - user2@test.com
                      date: 1602094554
                      module: 1
                      id: HDn3WCz6g9gDaZhutXVQ
                      key: quiz/HDn3WCz6g9gDaZhutXVQ
                    - users:
                        - user0@test.com
                        - user1@test.com
                        - user2@test.com
                      date: 1702094554
                      module: 1
                      id: SqQBZEt4j9Q7cr2NewQa
                      key: quiz/SqQBZEt4j9Q7cr2NewQa
                    - users:
                        - user0@test.com
                        - user1@test.com
                        - user2@test.com
                      date: 102094554
                      module: 1
                      id: m1BLUeflaSqPf0WYupRu
                      key: quiz/m1BLUeflaSqPf0WYupRu
          description: Delete user
        '503':
          content:
            application/json:
              example:
                data: None
                error: |
                  Traceback (most recent call last):
                      File "/home/source/Workspace/Python/hccb-backend/src/resolvers/user.py", line 38, in post
                      user.email = data['email']
                  KeyError: 'email'
          description: Error
  /users/add:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                users:
                  type: array
                  items:
                    type: object
                    properties:
                      email:
                        type: string
                      key:
                        type: string
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                data:
                  users:
                    - email: user1@test.com
                      name: user1
                    - email: user2@test.com
                      name: user1
                    - email: user3@test.com
                      name: user1
                error: None
          description: Add Users in BULK
  /user/get:
    get:
      parameters:
        - name: email
          in: query
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              example:
                error: None
                key: user/@temp_doc_id
                data:
                  id: cfJEpMmMXZZcjNmXu8x1
          description: Get user with email
        '503':
          content:
            application/json:
              example:
                data: None
                error: |
                  Traceback (most recent call last):
                      File "/home/source/Workspace/Python/hccb-backend/src/resolvers/user.py", line 38, in post
                      user.email = data['email']
                  KeyError: 'email'
          description: Error
  /quiz/check:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                key:
                  type: string
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                error: null
                data: true
          description: Check if user is valid for provided Quiz
  /quiz/add:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                date:
                  type: number
                module:
                  type: number
                users:
                  type: array
                  items:
                    type: string
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                error: null
                data:
                  users:
                    - user0@test.com
                    - user1@test.com
                    - user2@test.com
                  date: 16083758435
                  module: 1
                  key: quiz/xpYkGvpENJEUSz2TBiSv
          description: Add Quiz
  /quiz/add-data:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                data:
                  type: array
                  items:
                    type: object
                    properties:
                      email:
                        type: string
                      key:
                        type: string
                      title:
                        type: string
                      description:
                        type: string
                      qualities:
                        type: array
                        items:
                          type: string
                      suggestions:
                        type: array
                        items:
                          type: string
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                data:
                  users:
                    - email: user1@test.com
                      name: user1
                    - email: user2@test.com
                      name: user1
                    - email: user3@test.com
                      name: user1
                error: None
          description: Add User response for a quiz
  /mail:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                emails:
                  type: array
                  items:
                    type: string
                quiz_id:
                  type: string
                date:
                  type: number
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              example:
                error: null
                data: true
          description: mail list of users with quiz link
          
  /quiz/responses:
    get:
      parameters:
        - name: email
          in: query
          schema:
            type: string
        - name: quiz_id
          in: query
          schema:
            type: string
          required: true
      responses:
        '200':
          content:
            application/json:
              example:
                error: None
                key: user/@temp_doc_id
                data:
                  id: cfJEpMmMXZZcjNmXu8x1
          description: list all responses for a particular quiz
        '503':
          content:
            application/json:
              example:
                data: None
                error: |
                  Traceback (most recent call last):
                      File "/home/source/Workspace/Python/hccb-backend/src/resolvers/user.py", line 38, in post
                      user.email = data['email']
                  KeyError: 'email'
          description: Error
  /quizzes:
    get:
      responses:
        '200':
          content:
            application/json:
              example:
                error: None
                key: user/@temp_doc_id
                data:
                  id: cfJEpMmMXZZcjNmXu8x1
          description: Get all quizzes
        '503':
          content:
            application/json:
              example:
                data: None
                error: |
                  Traceback (most recent call last):
                      File "/home/source/Workspace/Python/hccb-backend/src/resolvers/user.py", line 38, in post
                      user.email = data['email']
                  KeyError: 'email'
          description: Error
